syntax = "proto3"

package services.alarms 

// service will have a process to report ACTIVE alarms


// service will have an rpc to 

service Alarms {
    // A stream of active alarms
    rpc getActiveAlarms(AlarmRequest) return (stream Alarms) {}

    // request for alarm logs
    rpc getAlarmLogs(AlarmLogRequest) returns (AlarmLogResponse)
}

message AlarmRequest {}

message AlarmData {
    string device_name = 1;
    alarm type // analog or digital
    TimeStamp active_time
    optional TimeStamp resolved_time // should this be here? 
}

message AlarmLogRequest {
    optional string device_name = 1;
    optional TimeStamp date_from = 2;
    optional TimeStamp date_to = 3;
    // other filters?? 
}

message AlarmLogResonse {
    repeated AlarmData alarm_data = 1;
}