[package]
name = "acorn-alarms-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
tokio = { version = "1.49.0", features = ["rt-multi-thread","macros"] }
tonic = "0.14.2"
prost = "0.14.3"
prost-types = "0.14.3"
tokio-stream = { version = "0.1.18", features = ["sync"] }
tonic-prost = "0.14.2"
futures = "0.3.31"
chrono = "0.4.43"
rust-env-var-lib = { git = "https://github.com/fermi-ad/rust-env-var-lib.git", tag = "v1.1.0" }
rust-pubsub-lib = { git = "https://github.com/fermi-ad/rust-pubsub-lib.git", rev = "052f2be51d333c249300743fce3508612dcd87ef" }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"

[build-dependencies]
protoc-bin-vendored = "3.2"
tonic-prost-build = "0.14.2"
