//! Types describing publish requests, retries, and outcomes.

use crate::{model::key::Key, proto::common::alarm::Status};

/// Shared details carried by each publish request.
#[derive(Clone)]
pub struct PublishDetails {
    /// Monotonic identifier for the publish request.
    pub id: u64,
    /// Alarm identity associated with the publish.
    pub key: Key,
    /// Alarm status payload to publish.
    pub status: Status,
}

/// A publish request initiated either automatically or by a user action.
#[derive(Clone)]
pub enum Publish {
    /// A publish generated by automated alarm processing.
    Automated(PublishDetails),
    /// A publish generated by a user action.
    User(PublishDetails),
}

impl Publish {
    /// Returns a shared reference to the underlying publish details.
    pub fn details_ref(&self) -> &PublishDetails {
        match self {
            Publish::Automated(details) => details,
            Publish::User(details) => details,
        }
    }

    /// Consumes the request and returns its underlying publish details.
    pub fn into_details(self) -> PublishDetails {
        match self {
            Publish::Automated(details) => details,
            Publish::User(details) => details,
        }
    }

    /// Returns whether the publish originated from a user action.
    pub fn is_user_initiated(&self) -> bool {
        matches!(self, Publish::User(_))
    }
}

/// A publish request paired with its retry attempt count.
#[derive(Clone)]
pub struct PublishAttempt {
    /// The publish request being attempted.
    pub request: Publish,
    /// The number of attempts made so far.
    pub attempt_count: u8,
}

impl PublishAttempt {
    /// Creates a new publish attempt starting at attempt one.
    pub fn new(request: Publish) -> Self {
        Self {
            request,
            attempt_count: 1,
        }
    }

    /// Returns a shared reference to the underlying publish details.
    pub fn details_ref(&self) -> &PublishDetails {
        self.request.details_ref()
    }

    /// Consumes the attempt and returns the underlying publish request.
    pub fn into_request(self) -> Publish {
        self.request
    }

    /// Increments the attempt count, saturating at the maximum [`u8`] value.
    pub fn increment_attempt(&mut self) {
        self.attempt_count = self.attempt_count.saturating_add(1);
    }
}

/// The result of publishing one request or a batch of requests.
pub enum PublishOutcome {
    /// Results for a batch publish operation.
    Batch(Vec<PublishResult>),
    /// Result for a single publish operation.
    Single(PublishResult),
}

/// Result type for a publish attempt.
pub type PublishResult = Result<PublishAttempt, PublishAttempt>;
