#!/usr/bin/python

# measure time to request multiple device readings via GraphQL
#
# results (1000 devices per request)
#  0.0607781093567609 sec
#  0.0679989792406559 sec
#  0.0679213460534811 sec
#  0.0580099085345864 sec

from python_graphql_client import GraphqlClient
from time import perf_counter

def main():
  # query = 'query get { acceleratorData(deviceList: ['
  devs = []

  with open('devices.txt') as file:
    for i, line in enumerate(file):
      if i == 1000: break
      line = line.strip()
      devs.append(line)
      # print(line)
      # query += '"' + line + '",'

  # query += ']) { data { timestamp result { ... on Scalar { scalarValue } } } } }'
  # query += ']) { data { timestamp } } } }'
  # print(query)

  query = ''' query get($dl: [String!]!) {
                acceleratorData(deviceList: $dl) {
                  data {
                    timestamp result {
                      ... on Scalar { scalarValue }
              } } } } '''

  client = GraphqlClient('https://acsys-proxy.fnal.gov:8001/acsys')

  start_time = perf_counter()

  # result = client.execute(query)
  result = client.execute(query, devs)

  end_time = perf_counter()

  # print(result)
  print(end_time - start_time)

if __name__ == '__main__': main()
