name: Rust Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  run-tests-and-coverage:
    uses: fermi-ad/.github/.github/workflows/rust-deployment.yaml@swb_v2
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
    with:
      references-internal-git-repo: true
