name: Rust Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  run-tests-and-coverage:
    uses: fermi-ad/.github/.github/workflows/rust-deployment.yaml@76f13236aaddfed6f43b666d241d4ca4dbe621cf
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
    with:
      pull-git-submodules: true
      references-internal-git-repo: true
      static-dependencies: 'libcurl4-openssl-dev librdkafka-dev libsasl2-dev'
