name: Rust Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests-and-coverage:
    uses: fermi-ad/.github/.github/workflows/rust-integration.yaml@swb_v2
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
    with:
      references-internal-git-repo: true
