name: Rust Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests-and-coverage:
    uses: fermi-ad/.github/.github/workflows/rust-integration.yaml@2fb2c616dc6d62380a7dbfc9bd63d70cea6feb1c
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
    with:
      pull-git-submodules: true
      references-internal-git-repo: true
      static-dependencies: 'libcurl4-openssl-dev librdkafka-dev libsasl2-dev'
